stages:
  - build

build_job:
  stage: build
  script:
    - |
      CI_COMMIT_SHA_SHORT="$(git rev-parse --short HEAD)"
      if git diff HEAD~ --name-only | egrep 'Dockerfile|requirements.txt|config.py|binder_gallery/|migrations/|manage.py'; then
        echo "####### gesiscss/binder-gallery:$CI_COMMIT_SHA_SHORT"
        docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
        docker build -t gesiscss/binder-gallery:$CI_COMMIT_SHA_SHORT .
        docker push gesiscss/binder-gallery:$CI_COMMIT_SHA_SHORT
      fi;
  only:
    - master
  tags:
    - binder_gallery
  when: on_success
  allow_failure: false
  dependencies: []
  retry: 1
