"""empty message

Revision ID: 26dbeb68791e
Revises: 53ed88ea18c1
Create Date: 2019-08-05 11:09:30.843900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26dbeb68791e'
down_revision = '53ed88ea18c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo', sa.Column('last_ref', sa.String(), server_default='master', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo', 'last_ref')
    # ### end Alembic commands ###
