"""empty message

Revision ID: 53ed88ea18c1
Revises: 522f8e14514c
Create Date: 2019-06-13 11:33:06.241399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '53ed88ea18c1'
down_revision = '522f8e14514c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('binder_launch', sa.Column('origin', sa.String(), nullable=True))
    op.create_index(op.f('ix_binder_launch_origin'), 'binder_launch', ['origin'], unique=False)
    # NOTE index for previous partitions are not created automatically
    # op.create_index('binder_launch_y2019_origin_idx', 'binder_launch_y2019', ['origin'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_binder_launch_origin'), table_name='binder_launch')
    op.drop_column('binder_launch', 'origin')
    # ### end Alembic commands ###
