"""empty message

Revision ID: 60f7b25ebfe7
Revises: 9b0e3f3da8cf
Create Date: 2019-01-31 16:12:53.686288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f7b25ebfe7'
down_revision = '9b0e3f3da8cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_spec', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('binder_launch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schema', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('spec', sa.String(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_binder_launch_timestamp'), 'binder_launch', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_binder_launch_timestamp'), table_name='binder_launch')
    op.drop_table('binder_launch')
    op.drop_table('repo')
    # ### end Alembic commands ###
