"""empty message

Revision ID: 95ebbf30bba6
Revises: 60f7b25ebfe7
Create Date: 2019-01-31 17:14:20.668331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ebbf30bba6'
down_revision = '60f7b25ebfe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_repo_provider_spec'), 'repo', ['provider_spec'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repo_provider_spec'), table_name='repo')
    # ### end Alembic commands ###
