"""empty message

Revision ID: 9b0e3f3da8cf
Revises: 86a01e4a0f97
Create Date: 2019-01-30 18:20:52.907080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0e3f3da8cf'
down_revision = '86a01e4a0f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('created_by_gesis', 'binder_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('created_by_gesis', 'repo_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('created_by_gesis', 'repo_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('created_by_gesis', 'binder_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
