"""empty message

Revision ID: fcc81e19b86d
Revises: 
Create Date: 2019-03-06 17:17:26.582086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc81e19b86d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('created_by_gesis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('repo_url', sa.String(), nullable=False),
    sa.Column('binder_url', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position')
    )
    op.create_table('featured_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('repo_url', sa.String(), nullable=False),
    sa.Column('binder_url', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position')
    )
    op.create_table('repo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_spec', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_provider_spec'), 'repo', ['provider_spec'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('binder_launch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schema', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('spec', sa.String(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_binder_launch_repo_id'), 'binder_launch', ['repo_id'], unique=False)
    op.create_index(op.f('ix_binder_launch_timestamp'), 'binder_launch', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_binder_launch_timestamp'), table_name='binder_launch')
    op.drop_index(op.f('ix_binder_launch_repo_id'), table_name='binder_launch')
    op.drop_table('binder_launch')
    op.drop_table('user')
    op.drop_index(op.f('ix_repo_provider_spec'), table_name='repo')
    op.drop_table('repo')
    op.drop_table('featured_project')
    op.drop_table('created_by_gesis')
    # ### end Alembic commands ###
